app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user: # "all.xml" fichier contenant les routes prédéfinies par défaut de FOSUserbundle (personnalisable dans un autre fichier xml)
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"